### ISSUE TITLE
PatternSyntaxException encountered on Windows

### ISSUE THREAD

**Issue by rentallect** [SeanRoy/lambduh-maven-plugin#1] opened 2015-08-11 15:37 UTC
Sean,

I do most of my dev on a Mac, but am trying to use your nifty plugin on a Windows box, and I'm getting the following error:

Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at com.github.seanroy.plugins.LambduhMojo.execute(LambduhMojo.java:98)
        ...

I think this can be resolved by changing line 98 of your code from:

   String[] pieces = functionCode.split(File.separator);

to this:

   String[] pieces = functionCode.split(File.separatorChar);

**Comment by SeanRoy** [comment] 2015-08-11 16:13
OK, thanks for the comment, I'll look into this as soon as I can.

**Comment by SeanRoy** [comment] 2015-08-11 16:49
The problem is that the file separator on windows is a backslash, which needs to be quoted.  I believe I resolved the problem by using Pattern.quote(File.separator).

I just deployed this so please look for version 1.0.2.  It can take an hour or two before it's available in the maven central repository.

**Comment by rentallect** [comment] 2015-08-11 17:44
Will do. Thanks.

**Comment by SeanRoy** [comment] 2015-08-12 13:06
Did this solve your problem?  Let me know so I can close this issue, thanks!

**Closed** 2015-08-13 04:08 UTC

**Comment by rentallect** [comment] 2015-08-13 10:53
Sorry for delay. Yes, the update is working fine. Thanks.
